
import "./globals.css"
import AppBar from '@mui/material/AppBar'
import Box from '@mui/material/Box'
import Toolbar from '@mui/material/Toolbar'
import Typography from '@mui/material/Typography'
import Button from '@mui/material/Button'
import IconButton from '@mui/material/IconButton'
import MenuIcon from '@mui/icons-material/Menu'

import Link from 'next/link'

export const metadata = {
  title: "Book & Movie Journal",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html>
      <body suppressHydrationWarning>
        <div className="root-container">
          <Box sx={{ flexGrow: 1 }}>
            <AppBar position="static">
              <Toolbar>
                <IconButton
                  size="large"
                  edge="start"
                  color="inherit"
                  aria-label="menu"
                  sx={{ mr: 2 }}
                >
                  <MenuIcon />
                </IconButton>
                <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
                  <Link  href="/">Book & Movie Journal</Link>
                </Typography>
                <Link  href="/login">Login</Link>
              </Toolbar>
            </AppBar>
          </Box>
          {children}
        </div>
      </body>
    </html>
  );
}
